apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-21018
  labels:
    app: nginx-deployment-21018
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment-21018
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx-deployment-21018
        tier: frontend
    spec: # Pod spec
      containers:
      - name: nginx-container-21018
        image: nginx:1.21
                ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
            key: welcome_msg
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
nginx/html
    volumes:
    - name: nginx-pvc-21018
      persistentVolumeClaim:
        claimName: nginx-pvc
