apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    environment: dev
spec:
  host: webapp-21018-route-webapp.apps.lab.okd.local
  to:
    kind: Service
    name: {{ .Values.appName }}
    weight: 100
  port:
    targetPort: flask
  wildcardPolicy: None
