apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route-21018
  labels:
    app: nginx-deployment-21018
    environment: dev
spec:
  host: nginx-route-21018-webapp.local
  to:
    kind: Service
    name: nginx-service-21018
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
